In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('IMDB Dataset.csv')

In [3]:
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [4]:
df['sentiment'].value_counts()

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

In [5]:
map={'positive':1,'negative':0}
df['sentiment']=df['sentiment'].map(map).astype(int)

In [6]:
df

                                                  review  sentiment
0      One of the other reviewers has mentioned that ...          1
1      A wonderful little production. <br /><br />The...          1
2      I thought this was a wonderful way to spend ti...          1
3      Basically there's a family where a little boy ...          0
4      Petter Mattei's "Love in the Time of Money" is...          1
...                                                  ...        ...
49995  I thought this movie did a down right good job...          1
49996  Bad plot, bad dialogue, bad acting, idiotic di...          0
49997  I am a Catholic taught in parochial elementary...          0
49998  I'm going to have to disagree with the previou...          0
49999  No one expects the Star Trek movies to be high...          0

[50000 rows x 2 columns]

In [7]:
train_data_len=len(df)*0.80

In [8]:
test_data_len=len(df)-train_data_len

In [9]:
train_data = df.iloc[0:int(train_data_len), :]  
test_data = df.iloc[int(train_data_len):, :]

In [10]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [11]:
vectorize_layer = layers.TextVectorization(
    max_tokens=30,
    output_mode="int",
)

2026-04-02 10:45:53.414282: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M2
2026-04-02 10:45:53.414312: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 8.00 GB
2026-04-02 10:45:53.414319: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 2.67 GB
2026-04-02 10:45:53.414657: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2026-04-02 10:45:53.414974: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)

In [12]:
vectorize_layer.adapt(df['review'].values)
X = vectorize_layer(train_data['review'].values)
y = train_data['sentiment'].values

2026-04-02 10:45:53.680026: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.

In [13]:
model_lstm = tf.keras.Sequential([
    tf.keras.layers.Embedding(10000, 128),
    tf.keras.layers.LSTM(64),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model_lstm.compile(
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

model_lstm.fit(X, y, epochs=5, batch_size=32)

Epoch 1/5
1250/1250 [==============================] - 201s 158ms/step - loss: 0.6934 - accuracy: 0.4951
Epoch 2/5
1250/1250 [==============================] - 202s 162ms/step - loss: 0.6932 - accuracy: 0.4989
Epoch 3/5
1250/1250 [==============================] - 199s 159ms/step - loss: 0.6932 - accuracy: 0.4992
Epoch 4/5
1250/1250 [==============================] - 200s 160ms/step - loss: 0.6932 - accuracy: 0.5031
Epoch 5/5
1250/1250 [==============================] - 196s 157ms/step - loss: 0.6932 - accuracy: 0.4983

In [14]:
model_gru = tf.keras.Sequential([
    tf.keras.layers.Embedding(10000, 128),
    tf.keras.layers.GRU(64),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model_gru.compile(
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

model_gru.fit(X, y, epochs=5, batch_size=32)

Epoch 1/5
1250/1250 [==============================] - 175s 138ms/step - loss: 0.6938 - accuracy: 0.5005
Epoch 2/5
1250/1250 [==============================] - 181s 144ms/step - loss: 0.6942 - accuracy: 0.5019
Epoch 3/5
1250/1250 [==============================] - 1000s 801ms/step - loss: 0.6936 - accuracy: 0.4989
Epoch 4/5
1250/1250 [==============================] - 186s 149ms/step - loss: 0.6941 - accuracy: 0.5033
Epoch 5/5
1250/1250 [==============================] - 196s 157ms/step - loss: 0.6942 - accuracy: 0.4975